#+TITLE: Readme

* Contributing

** Truth is not enough. It must be received by those who most need it. Focus on reception.

* Core Message

** Q is a fraud because his actions contradict his own message.

This above all else.

If only Q can be trusted, then this is the only message that is left.

* If there must be a secondary message...

** Why?

If the core message lands, we must be able to answer the "why". If Q is not who
he pretends to be, who is he? Why would someone do this? What is the benefit?

* Compassion

http://cultresearch.org/recovering-from-cult-experiences-recognize-resolve-aftereffects/

https://baytreepublish.com/take-back-your-life/

#+BEGIN_QUOTE
...the process of leaving the group and then putting one’s life (and also one’s
mind) together can be – and often is – a very troubled time, fraught with
anxiety, indecision, anger, worry, fear, either too little or too much sleep,
confusion, guilt, loneliness, the inability to think straight, flashbacks,
shame, depression, suicidal thoughts, identity crises, loss of memory, and so on
– in other words, a wild ride on an emotional roller coaster.
#+END_QUOTE

#+BEGIN_QUOTE
When I work one on one with former cult members, there are several things I ask
them to do that usually help, and that involves deconstructing the system to
gain a full understanding of what was at play. And of course to recognize that
because of what Lifton calls “milieu control” – control of information, of
social contact, of outside realities – you were playing with less than a full
deck.
#+END_QUOTE
